manifest:
  version: "1.2"

  # 이 레포(애플리케이션) 위치. 워크플로우에서 checkout을 app/으로 하므로 app으로 고정
  self:
    path: .

  projects:
    - name: nrf
      # ✅ 절대 URL로 명시 (remote/url-base 안 씀)
      url: https://github.com/nrfconnect/sdk-nrf.git
      path: nrf
      revision: v3.0.2
      import: true
